{
  "id": "5f8db27d15a311001edf723a",
  "title": "AtCoderのPythonでMemoryErrorを出すとREになる",
  "created": 1603121792,
  "updated": 1603121977,
  "lines": [
    {
      "id": "5f8db27d15a311001edf723a",
      "text": "AtCoderのPythonでMemoryErrorを出すとREになる",
      "userId": "582e63d27c56960011aff09e",
      "created": 1603121792,
      "updated": 1603121792
    },
    {
      "id": "5f8db290aff09e00005a7889",
      "text": "code:python",
      "userId": "582e63d27c56960011aff09e",
      "created": 1603121808,
      "updated": 1603121812
    },
    {
      "id": "5f8db292aff09e00005a788a",
      "text": " xs = [0] * (10 ** 9)",
      "userId": "582e63d27c56960011aff09e",
      "created": 1603121812,
      "updated": 1603121812
    },
    {
      "id": "5f8db293aff09e00005a788b",
      "text": "[https://gyazo.com/7a3c6eaea86deec2d0977e4c21e18fa7]",
      "userId": "582e63d27c56960011aff09e",
      "created": 1603121812,
      "updated": 1603121845
    },
    {
      "id": "5f8db2b5aff09e00005a788c",
      "text": "",
      "userId": "582e63d27c56960011aff09e",
      "created": 1603121845,
      "updated": 1603121845
    },
    {
      "id": "5f8db27faff09e0000ccd14a",
      "text": "こういうケースは、実際にメモリを確保してメモリ制限を超えるより前に、Python処理系が「そんな量の確保はできないよ」と実行時例外を投げている。なのでジャッジサーバ上の表示はMLEではなくREになる。",
      "userId": "582e63d27c56960011aff09e",
      "created": 1603121792,
      "updated": 1603121977
    },
    {
      "id": "5f8db2ccaff09e0000ccd14b",
      "text": "",
      "userId": "582e63d27c56960011aff09e",
      "created": 1603121868,
      "updated": 1603121868
    }
  ]
}