{
  "id": "6090ec0ea287e6002291a32e",
  "title": "Hatena2015-06-28",
  "created": 1435417200,
  "updated": 1435417200,
  "lines": [
    {
      "id": "6090ec32aff09e00003e0249",
      "text": "Hatena2015-06-28",
      "created": 1435417200,
      "updated": 1435417200,
      "userId": "582e63d27c56960011aff09e"
    },
    {
      "id": "6090ec32aff09e00003e024a",
      "text": "code:hatena",
      "created": 1435417200,
      "updated": 1435417200,
      "userId": "582e63d27c56960011aff09e"
    },
    {
      "id": "6090ec32aff09e00003e024b",
      "text": " <body>",
      "created": 1435417200,
      "updated": 1435417200,
      "userId": "582e63d27c56960011aff09e"
    },
    {
      "id": "6090ec32aff09e00003e024c",
      "text": " *1435471207*Chainer「NameError: global name 'drv' is not defined」",
      "created": 1435417200,
      "updated": 1435417200,
      "userId": "582e63d27c56960011aff09e"
    },
    {
      "id": "6090ec32aff09e00003e024d",
      "text": " Chainerを使って実装をしていて「NameError: global name 'drv' is not defined」というエラーが出た場合、周囲のソースを読んでみたりしてもよくわからず、CUDA周りの何かなのだろうかとかしばらく悩んだけども、このエラーを再現させるコードは",
      "created": 1435417200,
      "updated": 1435417200,
      "userId": "582e63d27c56960011aff09e"
    },
    {
      "id": "6090ec32aff09e00003e024e",
      "text": " >||",
      "created": 1435417200,
      "updated": 1435417200,
      "userId": "582e63d27c56960011aff09e"
    },
    {
      "id": "6090ec32aff09e00003e024f",
      "text": " Variable(1) + 1",
      "created": 1435417200,
      "updated": 1435417200,
      "userId": "582e63d27c56960011aff09e"
    },
    {
      "id": "6090ec32aff09e00003e0250",
      "text": " ||<",
      "created": 1435417200,
      "updated": 1435417200,
      "userId": "582e63d27c56960011aff09e"
    },
    {
      "id": "6090ec32aff09e00003e0251",
      "text": " で十分。Variableの引数がnumpy.ndarrayやpycuda.gpuarray.GPUArrayではない場合に起きる。うっかり1-of-Kにすべきところでそのままの値を入れたのが自分の場合の失敗原因だった。",
      "created": 1435417200,
      "updated": 1435417200,
      "userId": "582e63d27c56960011aff09e"
    },
    {
      "id": "6090ec32aff09e00003e0252",
      "text": " ",
      "created": 1435417200,
      "updated": 1435417200,
      "userId": "582e63d27c56960011aff09e"
    },
    {
      "id": "6090ec32aff09e00003e0253",
      "text": " 「Variableの引数が～でない時に起こる」はわかった。「Variableの引数が～でないときに、なぜ起こるか」はざっとコードを眺めただけではわからない。だけど「Variableの引数が～でない時にこのエラーが起こらないようにする」という上では、そもそもVariableは仕様上～しか受け取らないってことになっているんだから、__init__の時点で違うものが来ていたらアサーションエラーにすればいいだけだ。というわけで「なぜ」に関して深追いするのはやめた。",
      "created": 1435417200,
      "updated": 1435417200,
      "userId": "582e63d27c56960011aff09e"
    },
    {
      "id": "6090ec32aff09e00003e0254",
      "text": " </body>",
      "created": 1435417200,
      "updated": 1435417200,
      "userId": "582e63d27c56960011aff09e"
    },
    {
      "id": "6090ec32aff09e00003e0255",
      "text": "",
      "created": 1435417200,
      "updated": 1435417200,
      "userId": "582e63d27c56960011aff09e"
    },
    {
      "id": "6090ec32aff09e00003e0256",
      "text": "[はてなダイアリー 2015-06-28 https://nishiohirokazu.hatenadiary.org/archive/2015/06/28]",
      "created": 1435417200,
      "updated": 1435417200,
      "userId": "582e63d27c56960011aff09e"
    }
  ]
}